Repository sunpy/sunkit-pyvista, pull requests merged in 2021-08, with the labels that each got.

#62 Use pytest.skip() for figure tests
  sunkit_pyvista/tests/conftest.py
  sunkit_pyvista/tests/test_plotting.py
Labels: No Changelog Entry Needed

#61 Use PolyData for map meshes
  setup.cfg
  sunkit_pyvista/plotter.py
  sunkit_pyvista/tests/image_cache/field_lines_figure.png
  sunkit_pyvista/tests/image_cache/plot_map_with_functionality.png
  sunkit_pyvista/tests/test_pyvista.py
Labels: No Changelog Entry Needed

#59 Vendors in get_limb_coordinates to produce plot_limb method
  changelog/17.feature.rst
  changelog/59.feature.rst
  sunkit_pyvista/__init__.py
  sunkit_pyvista/plotter.py
  sunkit_pyvista/tests/image_cache/field_lines_figure.png
  sunkit_pyvista/tests/image_cache/plot_map_with_functionality.png
  sunkit_pyvista/tests/test_plotting.py
  sunkit_pyvista/tests/test_pyvista.py
  sunkit_pyvista/utils.py
Labels: No Changelog Entry Needed

#63 Doc build 2
  .gitignore
  docs/conf.py
  docs/examples/3d_map.rst
  docs/examples/_readme.txt
  docs/examples/index.rst
  docs/examples/setup.py
  docs/index.rst
  examples/3d_map.py
  examples/README.txt
  examples/plot_field_lines.py
  examples/plot_functionality.py
  setup.cfg
  sunkit_pyvista/plotter.py
Labels: No Changelog Entry Needed

#66 Adds the remaining examples as rst files
  docs/examples/3d_functionality.rst
  docs/examples/field_lines.rst
  examples/3d_functionality.py
  examples/field_lines.py
Labels: No Changelog Entry Needed, documentation

#70 Allows for a color function to be specified to plot_field_lines()
  changelog/70.feature.rst
  examples/field_lines.py
  sunkit_pyvista/plotter.py
  sunkit_pyvista/tests/image_cache/field_lines_figure.png
  sunkit_pyvista/tests/test_plotting.py
  sunkit_pyvista/tests/test_pyvista.py
Labels: enhancement
